rancho/chat/urls.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django.conf.urls.defaults import *

urlpatterns = patterns('rancho.chat.views',
    (r'^$','general_chat'),
    (r'^logs/$','logs'),
    (r'^create/$','send_message'),
    (r'^get_messages/$','get_and_display_messages'),
    (r'^disconnect/$','disconnect'),
    (r'^get_online_users/$','display_online_users'),
)

rancho/urls.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django.conf.urls.defaults import *

from rancho import settings

urlpatterns = patterns('django.views.generic.simple',
    (r'^$', 'redirect_to', {'url': 'dashboard/'}),
    (r'^legal_notice/$', 'direct_to_template', {'template': 'legal_notice.html'}, 'legal_notice'),
)

urlpatterns = urlpatterns + patterns('',

    (r'^notification/', include('rancho.notification.urls')),

    (r'^dashboard/$', 'rancho.user.views.dashboard'),
    (r'^milestones/$', 'rancho.user.views.milestones'),
    (r'^statistics/$', 'rancho.user.views.statistics'),

    (r'^auth/', include('rancho.auth.urls')),
    (r'^project/', include('rancho.project.urls')),
    (r'^company/', include('rancho.company.urls')),
    (r'^people/', include('rancho.user.urls')),
    (r'^calendar/', include('rancho.cal.urls')),
    (r'^search/', include('rancho.search.urls')),

    (r'^tinymce/', include('tinymce.urls')),
)

if getattr(settings, 'LOCAL_DEV', False):
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.MEDIA_ROOT}),
)

rancho/chat/models.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django.contrib.auth.models import User
from django.db import models
from rancho.project.models import Project

class Post(models.Model):

    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, blank=True)
    message = models.CharField(max_length=1000)
    project = models.ForeignKey(Project, null = True, blank = True)

class ChatData(models.Model):

    user = models.ForeignKey(User)
    project = models.ForeignKey(Project, null = True, blank = True)
    last_request = models.IntegerField()
    is_connected = models.BooleanField(default = False)

rancho/chat/forms.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django import forms
from django.utils.translation import ugettext_lazy as _
from rancho.chat.models import Post
import datetime



class ChatForm(forms.Form):

    message = forms.CharField(label = _('Message'), widget=forms.Textarea(attrs={'class':'fillx', 'rows': 2, 'id': 'message'}), error_messages={'required': _('The message cannot be blank.')})

    def __init__(self, request = None, *args, **kwargs):
        super(ChatForm, self).__init__(request,*args, **kwargs)

    def save(self, user, project, message = None):
        post = Post(
            date   = datetime.now(),
            message = message,
            author = user,
            project = project,
            )
        post.save()
        return post


class LogForm(forms.Form):

    from_date = forms.DateField(label=_('From date'), error_messages={'invalid':_('Invalid date format')}, required = False)
    to_date = forms.DateField(label=_('To date'), error_messages={'invalid':_('Invalid date format')}, required = False)

rancho/chat/views.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.template import loader, Context
from django.template.context import RequestContext
from rancho.chat.forms import ChatForm, LogForm
from rancho.chat.models import Post, ChatData
from rancho.project.models import Project

@login_required
def general_chat(request, p_id):
    SUMMARY_NUMBER = 15
    user = request.user
    project = get_object_or_404(Project, id=p_id)

    project.check_user_in_project_or_404(user)

    posts = Post.objects.filter(project = project)

    try:
        chat_data = ChatData.objects.get(project = project, user = user)
    except ChatData.DoesNotExist:
        chat_data = ChatData(user = user, project = project, last_request = -1)
        chat_data.save()
    chat_data.is_connected = True;
    chat_data.save()

    chat_form = ChatForm()

    recent_log = list(Post.objects.filter(project = project, date__lt = datetime.now()).order_by('date'))[-SUMMARY_NUMBER:]

    context = {'posts': posts, 'project': project, 'chat_form': chat_form, 'recent_log': recent_log}

    return render_to_response("chat/general.html", context,
                              context_instance = RequestContext(request))

@login_required
def send_message(request, p_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

    project.check_user_in_project_or_404(user)

    if request.method == 'POST':
        message = request.POST.get('message')
        if not message:
            return HttpResponse('', mimetype='text/html')
        new_post = Post(author = user,
                        date = datetime.now(),
                        project = project,
                        message = message)
        new_post.save()

    return HttpResponse('', mimetype='text/html')


@login_required
def get_and_display_messages(request, p_id):
    def get_messages(request, p_id):
        SUMMARY_NUMBER = 15
        user = request.user
        project = get_object_or_404(Project, id = p_id)

        project.check_user_in_project_or_404(user)

        try:
            chat_data = ChatData.objects.get(user = user, project = project)
        except ChatData.DoesNotExist:
            chat_data = ChatData(user = user, project = project, last_request = -1, is_connected = True)
            chat_data.save()
        posts = []
        if chat_data:
            posts = Post.objects.filter(project = project, id__gt = chat_data.last_request).order_by('date')
        else:
            posts = Post.objects.filter(project = project).order_by('-date')[-SUMMARY_NUMBER:]

        if posts:
            chat_data.last_request = posts[len(posts)-1].id

        chat_data.is_connected = True
        chat_data.save()
        return posts

    posts = get_messages(request, p_id)
    context = Context({'posts': posts})
    result = loader.get_template('chat/display_messages.html').render(context)
    return HttpResponse(result, mimetype='text/xml')

@login_required
def display_online_users(request, p_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

    project.check_user_in_project_or_404(user)

    chat_data_objects = ChatData.objects.filter(project = project, is_connected = True)
    result = ''
    users_online = [chat_data.user for chat_data in chat_data_objects]
    context = Context({'users': users_online})
    result = loader.get_template('chat/display_online_users.html').render(context)
    return HttpResponse(result, mimetype='text/xml')

@login_required
def disconnect(request, p_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

    project.check_user_in_project_or_404(user)

    try:
        chat_data = ChatData.objects.get(project = project, user = user)
    except ChatData.DoesNotExist:
        chat_data = ChatData(user = user, project = project, last_request = -1)
        chat_data.save()
    chat_data.is_connected = False;
    chat_data.save()
    return HttpResponse('')


@login_required
def logs(request, p_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

    form = LogForm()

    from_date = None
    to_date = None
    if request.method == 'GET':
        form = LogForm(request.GET)
        if form.is_valid():
            from_date = form.cleaned_data.get('from_date')
            to_date = form.cleaned_data.get('to_date')
    posts = Post.objects.filter(project = project)
    if from_date:
        posts = posts.exclude(date__lt = from_date)
    if to_date:
        # 1 day is added to the upper date because it also compares the
        # time and the time is the minimum as only the date was set.
        posts = posts.exclude(date__gt = to_date + timedelta(1))
    context = {'project': project, 'form': form, 'logs': posts}
    return render_to_response("chat/logs.html", context,
                              context_instance = RequestContext(request))

rancho/templates/chat/display_messages.html
{% load displaychatline %}
<taconite>
    <append select="#chat">
        {% for post in posts %}
            {% displaychatline post %}
        {% endfor %}
    </append>
</taconite>

rancho/templates/chat/display_online_users.html
{% load usernamegen %}
<taconite>
    <replaceContent select="#users_online">
        {% for user in users %}
            <p><strong>{% usernamegen user "fullname" %}</strong></p>
        {% endfor %}
    </replaceContent>
</taconite>

rancho/templates/chat/general.html
{% extends "project/basicproject.html" %}

{% load i18n pagination_tags usernamegen genmenu permissions_tags form_tags displayuserphoto displaychatline %}

{% block pagetitle %} {{ project.name }} | {% trans "Overview" %} {% endblock %}


{% block jquerypluginloader %}
<script type="text/javascript" src="/media/js/jquery/simplemodal.js"></script>
<script type="text/javascript" src="/media/js/jquery/taconite.js"></script>
{% endblock %}

{% block jquerycode %}
    function send_message() {
       var message = $("#message").val();
       url = '{% url rancho.chat.views.send_message project.id %}';
       $.post(url, {message: message});
       $("#message").val("");
	   return false;
    }

    var chat_div = "#chat";
    var scrollHeight = $(chat_div).attr("scrollHeight");

    function get_messages() {
       url = '{% url rancho.chat.views.get_and_display_messages project.id %}';
       $.get(url);
       var newScrollHeight = $(chat_div).attr("scrollHeight");
       if (!scrollHeight || newScrollHeight > scrollHeight) {
           scrollHeight = newScrollHeight;
           $(chat_div).attr({ scrollTop: $(chat_div).attr("scrollHeight") });
       }
       return false;
    }

    var getMessagesRefreshId = setInterval(function()
    {
        get_messages();
    }, 1000);

    var getUsersRefreshId = setInterval(function()
    {
        url = '{% url rancho.chat.views.display_online_users project.id %}';
        $.get(url);
    }, 15000);

    $(document).ready(
        function () {
		    $('#message').bind("keypress", function (event){
		        if (event.keyCode == 13 && !event.shiftKey)
		        {
		          send_message();
		          return false;
		        }
		        return true;
		    });

		    $('#message').focus();

		    $(window).unload(
		        function () {
		        	url = '{% url rancho.chat.views.disconnect project.id %}';
                    $.get(url);
					aler("lalal");
                }
            );

			url = '{% url rancho.chat.views.display_online_users project.id %}';
            $.get(url);
		}
    );
{% endblock %}

{% block menu %}
	{% genmenu "inproject" "chat" project.id %}
{% endblock %}

{% block area_name %}
    <p>{% trans "Chat" %}</p>
{% endblock %}

{% block mini_menu %}
    <br/>
    <a href="{% url rancho.chat.views.logs project.id %}">{% trans "View Chat Logs" %}</a>
{% endblock %}

{% block right_content %}
    <div class="widget"><p>{% trans "Users Online" %}</p></div>
    <div id="users_online">
    </div>
{% endblock %}

{% block main_content %}
    <div class="blue_section">
	    <div id="chat" style="height: 200px; background: #fff;" class="scrollable fillx">
	       {% if recent_log %}
		       {% for post in recent_log %}
		           {% displaychatline post "True" %}
		       {% endfor %}
	       <p style="text-align: center;"> -- {% trans "Recent conversation" %} --</p>
	       <br/><br/>
	       {% endif %}
	    </div>
	</div>

	<form action="" method="post">
      {% beginrequestbox "required" "" "" %}
        {% printfield  chat_form.message "none" %}
      {% endrequestbox %}
    </form>
    <br/>
    <div class="add_button">
        <a href="#" onClick="send_message(); $('#message').focus(); return false;">{% trans "Send" %}</a>
    </div>
    <div class="add_button_right"></div>
    <br/><br/>
{% endblock %}

rancho/templates/chat/logs.html
{% extends "project/basicproject.html" %}

{% load i18n pagination_tags usernamegen genmenu permissions_tags form_tags displayuserphoto displaychatline sidewidget %}

{% block pagetitle %} {{ project.name }} | {% trans "Overview" %} {% endblock %}


{% block jquerypluginloader %}
<script src="/media/js/jquery/jquery.ui.js" type="text/javascript" charset="utf-8"></script>
<script src="/media/js/jquery/ui/i18n/ui.datepicker-{{LANGUAGE_CODE}}.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/media/js/jquery/ui.theme.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
<link rel="stylesheet" href="/media/js/jquery/ui.datepicker.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
{% endblock %}

{% block jquerycode %}

     function attach_datepicker(id) {
        $(id).datepicker({
        nextText: '',
        prevText: '',
        showOn: 'both',
        buttonImage: '/media/basepage/images/icons/date_add.png',
        buttonImageOnly: true ,
        buttonText: 'Calendar',
        yearRange: '2008:2020',
        dateFormat: 'yy-mm-dd'});
     }

     $(document).ready(function(){
        attach_datepicker('#id_from_date');
        attach_datepicker('#id_to_date');
     });
{% endblock %}

{% block menu %}
	{% genmenu "inproject" "chat" project.id %}
{% endblock %}

{% block area_name %}
    <p>{% trans "View Chat Logs" %}</p>
{% endblock %}

{% block right_content %}
    {% sidewidget _("Information") "information"%}
    <p>{% trans "Here you can see the chat logs and get them from a date interval." %}</p>
    <p>{% trans "By setting no dates, all logs will be displayed." %}</p>
{% endblock %}

{% block main_content %}

    <form action="{% url rancho.chat.views.logs project.id %}" method="get">
      {% beginrequestbox "required" _("Choose dates") _("Choose the dates between which you'd like to view the logs or leave them blank to view all logs.") %}
        {% printfield  form.from_date "left" %}
        {% printfield  form.to_date "left" %}
      {% endrequestbox %}
      <input type="submit" value="{% trans "View Logs" %}"/>
    </form>
    <br/>

    {% if logs %}
    <h4>{% trans "Chat Logs:" %}</h4>
    <div style="margin: 5px 0 0 25px;">
	    {% autopaginate logs 20 %}
	    {% paginate %}
	           {% for log in logs %}
	               {% displaychatline log "True" %}
	           {% endfor %}
	       <br/><br/>
	    {% paginate %}
    </div>
    {% else %}
        <h4>{% trans "No logs found!" %}</h4>
    {% endif %}
{% endblock %}