rancho/milestone/urls.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django.conf.urls.defaults import *

urlpatterns = patterns('rancho.milestone.views',

    (r'^$', 'list'),
    url(r'^filter/(?P<status>\w+)/$', 'list', name = 'list_with_status'),
    (r'^create/$', 'create'),
    (r'^edit/(?P<milestone_id>\d+)/$', 'edit'),
    (r'^complete/(?P<milestone_id>\d+)/$', 'complete'),
    (r'^incomplete/(?P<milestone_id>\d+)/$', 'incomplete'),
    (r'^delete/(?P<milestone_id>\d+)/$', 'delete'),
    (r'^list_same_status/(?P<milestone_id>\d+)/$', 'list_with_same_status'),
)

rancho/urls.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from django.conf.urls.defaults import *

from rancho import settings

urlpatterns = patterns('django.views.generic.simple',
    (r'^$', 'redirect_to', {'url': 'dashboard/'}),
    (r'^legal_notice/$', 'direct_to_template', {'template': 'legal_notice.html'}, 'legal_notice'),
)

urlpatterns = urlpatterns + patterns('',

    (r'^notification/', include('rancho.notification.urls')),

    (r'^dashboard/$', 'rancho.user.views.dashboard'),
    (r'^milestones/$', 'rancho.user.views.milestones'),
    (r'^statistics/$', 'rancho.user.views.statistics'),

    (r'^auth/', include('rancho.auth.urls')),
    (r'^project/', include('rancho.project.urls')),
    (r'^company/', include('rancho.company.urls')),
    (r'^people/', include('rancho.user.urls')),
    (r'^calendar/', include('rancho.cal.urls')),
    (r'^search/', include('rancho.search.urls')),

    (r'^tinymce/', include('tinymce.urls')),
)

if getattr(settings, 'LOCAL_DEV', False):
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.MEDIA_ROOT}),
)

rancho/milestone/models.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from datetime import date, datetime
from django.contrib.auth.models import User
from django.db import models
from rancho.project.models import Project

class MilestoneManager(models.Manager):
    def get_late_milestones(self, project = None, order = '-due_date', user = None):
        milestones = Milestone.objects.filter(completion_date = None).order_by(order)
        if project:
            milestones = milestones.filter(project = project).order_by(order)
        if user:
            milestones = milestones.filter(models.Q(responsible = user) | models.Q(responsible = None)).order_by(order)
        return [milestone for milestone in milestones if milestone.is_late()]

    def get_upcoming_milestones(self, project = None, order = 'due_date', user = None):
        milestones = Milestone.objects.filter(completion_date = None).order_by(order)
        if project:
            milestones = milestones.filter(project = project).order_by(order)
        if user:
            milestones = milestones.filter(models.Q(responsible = user) | models.Q(responsible = None)).order_by(order)
        return [milestone for milestone in milestones if milestone.is_upcoming()]

    def get_complete_milestones(self, project = None, order = 'completion_date', user = None):
        milestones = Milestone.objects.all().exclude(completion_date = None).order_by(order)
        if project:
            milestones = milestones.filter(project = project).order_by(order)
        if user:
            milestones = milestones.filter(models.Q(responsible = user) | models.Q(responsible = None)).order_by(order)
        return milestones

class Milestone(models.Model):
    creator = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    #If null, all the project is responsible
    responsible = models.ForeignKey(User, related_name='responsible', null=True)
    title = models.CharField(max_length=500)
    creation_date = models.DateTimeField(default = datetime.now())
    due_date = models.DateTimeField()
    send_notification_email = models.BooleanField()
    completion_date = models.DateTimeField(null=True)
    sent_notification = models.BooleanField(default=False)

    objects = MilestoneManager()

    @models.permalink
    def get_absolute_url(self):
        return ('rancho.milestone.views.edit', [], {'p_id': self.project.id, 'milestone_id':self.id})

    def is_late(self):
        return self.due_date.date() <= date.today() and \
               not self.completion_date

    def is_upcoming(self):
        return self.due_date.date() > date.today() and \
               not self.completion_date

    def is_complete(self):
        return self.completion_date != None

    def get_status_name(self):
        if self.is_late():
            return 'late'
        elif self.is_upcoming():
            return 'upcoming'
        else:
            return 'complete'

    def _get_todolist(self):
        todolist_set = self.todo_milestone.all()
        if todolist_set:
            return todolist_set[0]
        return None

    todolist = property(_get_todolist)

rancho/milestone/views.py
########################################################################
# Rancho - Open Source Group/Project Management Tool
#    Copyright (C) 2008 The Rancho Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

from datetime import date
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core import urlresolvers
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from django.utils.translation import ugettext as _
from rancho.granular_permissions.permissions import PERMISSIONS_MILESTONE_VIEW, \
    PERMISSIONS_MILESTONE_CREATE, PERMISSIONS_MILESTONE_EDITDELETE, checkperm
from rancho.lib import utils
from rancho.lib.utils import events_log
from rancho.milestone.forms import NewMilestoneForm
from rancho.milestone.models import Milestone
from rancho.notification import models as notification
from rancho.project.models import Project

# Basic operations for this app
####################################################################################

@login_required
def list(request, p_id, status = ''):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

    if not checkperm(PERMISSIONS_MILESTONE_VIEW, user, project ):
        return HttpResponseForbidden(_('Forbidden Access'))
    late_milestones = []
    upcoming_milestones = []
    complete_milestones = []
    if status == 'late' or not status:
        late_milestones = Milestone.objects.get_late_milestones(project = project)
    if status == 'upcoming' or not status:
        upcoming_milestones = Milestone.objects.get_upcoming_milestones(project = project)
    if status == 'complete' or not status:
        complete_milestones = Milestone.objects.get_complete_milestones(project = project)
    context = {
        'project': project,
        'late_milestones': late_milestones,
        'upcoming_milestones': upcoming_milestones,
        'complete_milestones': complete_milestones,
        'view_alone': bool(status)
        }
    return render_to_response("milestone/milestones_list.html", context,
                              context_instance=RequestContext(request))

@login_required
def list_with_same_status(request, p_id, milestone_id):

    milestone = get_object_or_404(Milestone, id = milestone_id)

    return list(request, p_id, milestone.get_status_name())

@login_required
def create(request, p_id):

    user = request.user
    project = get_object_or_404(Project, id = p_id)
    users_in_project = project.get_users()

    if not checkperm(PERMISSIONS_MILESTONE_CREATE, user, project ):
        return HttpResponseForbidden(_('Forbidden Access'))

    users_to_notify = utils.get_users_to_notify(project, PERMISSIONS_MILESTONE_VIEW)

    if request.method == 'POST':
        form = NewMilestoneForm(utils.format_users_for_dropdown(user, users_to_notify), request.POST)

        if form.is_valid():
            mstone = form.save(user, project)

            if mstone.send_notification_email:
                #TODO: make a view milestone url to use here
                link_url = u"http://%s%s" % ( unicode(Site.objects.get_current()), urlresolvers.reverse('rancho.milestone.views.list', args = [p_id]))
                #link_url = u"http://%s%s" % ( unicode(Site.objects.get_current()), urlresolvers.reverse('rancho.message.views.read_add_comment', kwargs={'p_id': project.id, 'm_id':msg.id}),)
                if mstone.responsible: #just notify one person
                    notification.send([mstone.responsible], "milestone_new", {'link_url': link_url, 'milestone': mstone })
                else: #notify all users with perm
                    notification.send(users_to_notify, "milestone_new", {'link_url': link_url, 'milestone': mstone })

            events_log(user, 'A', mstone.title, mstone)
            request.user.message_set.create(message=_('Milestone "%s" successfully created.') % mstone.title)
            return HttpResponseRedirect(urlresolvers.reverse('rancho.milestone.views.list', args = [p_id]))

    else:
        form = NewMilestoneForm(utils.format_users_for_dropdown(user, users_in_project))

    context = { 'project': project,
               'newMilestone': form,
               }

    return render_to_response("milestone/create_milestone.html", context,
                                  context_instance=RequestContext(request))

@login_required
def edit(request, p_id, milestone_id):

    user = request.user
    project = get_object_or_404(Project, id = p_id)
    milestone = get_object_or_404(Milestone, id = milestone_id)
    users_in_project = project.get_users()

    if not checkperm(PERMISSIONS_MILESTONE_EDITDELETE, user, project, milestone) or milestone.project != project:
        return HttpResponseForbidden(_('Forbidden Access'))

    users_to_notify = utils.get_users_to_notify(project, PERMISSIONS_MILESTONE_VIEW)

    if request.method=='POST':
        form = NewMilestoneForm(utils.format_users_for_dropdown(user, users_to_notify), request.POST)

        if form.is_valid():

            user_id = int(form.cleaned_data['responsible'])
            if user_id != 0:
                milestone.responsible = get_object_or_404(User, id = user_id)
            else:
                milestone.responsible = None
                milestone.completion_date = None
            old_milestone_title = milestone.title
            milestone.title = form.cleaned_data['title']
            milestone.due_date = form.cleaned_data['due_date']
            milestone.send_notification_email = form.cleaned_data['send_notification_email']
            milestone.save()

            if milestone.send_notification_email:
                link_url = u"http://%s%s" % ( unicode(Site.objects.get_current()), urlresolvers.reverse('rancho.milestone.views.list', args = [p_id]))
                #link_url = u"http://%s%s" % ( unicode(Site.objects.get_current()), urlresolvers.reverse('rancho.message.views.read_add_comment', kwargs={'p_id': project.id, 'm_id':msg.id}),)
                if milestone.responsible: #just notify one person
                    notification.send([milestone.responsible], "milestone_updated", {'link_url': link_url, 'milestone': milestone, 'old_milestone_title': old_milestone_title})
                else: #notify entire project
                    notification.send(users_to_notify, "milestone_updated", {'link_url': link_url, 'milestone': milestone, 'old_milestone_title': old_milestone_title })

            events_log(user, 'U', milestone.title, milestone)
            request.user.message_set.create(message=_('Milestone successfully edited.'))
    else:
        responsible_index = 0
        if milestone.responsible:
            responsible_index = milestone.responsible.id
        data = {'title': milestone.title,
                'due_date': milestone.due_date.date(),
                'responsible': responsible_index,
                'send_notification_email': milestone.send_notification_email}
        form = NewMilestoneForm(utils.format_users_for_dropdown(user, users_in_project), data)

    context = {'project': project,
               'milestone': milestone,
               'newMilestone': form,
               }
    return render_to_response("milestone/edit_milestone.html", context, context_instance = RequestContext(request))


@login_required
def complete(request, p_id, milestone_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)
    milestone = get_object_or_404(Milestone, id = milestone_id)
    if not checkperm(PERMISSIONS_MILESTONE_VIEW, user, project ):
        return HttpResponseForbidden(_('Forbidden Access'))
    if not milestone.completion_date:
        milestone.completion_date = date.today()
        milestone.responsible = user
        if milestone.todolist:
            for todo in milestone.todolist.get_todos():
                todo.responsible = user
                todo.completion_date = milestone.completion_date
                todo.save()
        # PERMISSIONS
        milestone.save()
        events_log(user, 'COMP', milestone.title, milestone)
    return HttpResponseRedirect(urlresolvers.reverse('rancho.milestone.views.list', args = [p_id]))

@login_required
def incomplete(request, p_id, milestone_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)
    milestone = get_object_or_404(Milestone, id = milestone_id)
    if not checkperm(PERMISSIONS_MILESTONE_VIEW, user, project ):
        return HttpResponseForbidden(_('Forbidden Access'))
    if milestone.completion_date:
        milestone.completion_date = None
        # PERMISSIONS
        if milestone.todolist:
            for todo in milestone.todolist.get_todos():
                todo.responsible = user
                todo.completion_date = None
                todo.save()
        milestone.save()
        events_log(user, 'ICOMP', milestone.title, milestone)
    return HttpResponseRedirect(urlresolvers.reverse('rancho.milestone.views.list', args = [p_id]))

@login_required
def delete(request, p_id, milestone_id):
    user = request.user
    project = get_object_or_404(Project, id = p_id)

rancho/templates/milestone/create_milestone.html
{% extends "project/basicproject.html" %}

{% load i18n usernamegen genmenu form_tags %}

{% block pagetitle %} {{ project.name }} | {% trans "New Milestone" %} {% endblock %}

{% block jquerypluginloader %}
<script src="/media/js/jquery/jquery.ui.js" type="text/javascript" charset="utf-8"></script>
<script src="/media/js/jquery/ui/i18n/ui.datepicker-{{LANGUAGE_CODE}}.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/media/js/jquery/ui.theme.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
 <link rel="stylesheet" href="/media/js/jquery/ui.datepicker.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
{% endblock %}

{% block jquerycode %}
     $(document).ready(function(){
        $('#id_due_date').datepicker({
        nextText: '',
        prevText: '',
        showOn: 'both',
        buttonImage: '/media/basepage/images/icons/date_add.png',
        buttonImageOnly: true ,
        buttonText: 'Calendar',
        yearRange: '2008:2020',
        dateFormat: 'yy-mm-dd'});
     });
{% endblock %}
{% block area_name %}
    <p>{% trans "Add a new milestone" %}</p>
{% endblock %}

{% block menu %}
	{% genmenu "inproject" "milestones" project.id %}
{% endblock %}

{% block right_content %}
{% endblock %}

{% block main_content %}
	<form action="{% url milestone.views.create p_id=project.id %}" method="post">
		{% beginrequestbox "required" _("Milestone") _("All these fields are required")  %}
			{% printfield  newMilestone.title "left" %}
			{% printfield  newMilestone.responsible "left" %}
			{% printfield  newMilestone.due_date "left" %}
	    {% endrequestbox %}

		{% beginrequestbox "notrequired" _("Other Info") _("All fields in this section are optional.")  %}
			{% printfield  newMilestone.send_notification_email "right" %}
	    {% endrequestbox %}

		{% printformfooter _("Submit Milestone") _("Cancel") "rancho.milestone.views.list project.id" %}
    </form>
{% endblock %}

rancho/templates/milestone/edit_milestone.html
{% extends "project/basicproject.html" %}

{% load i18n usernamegen modalconfirm genmenu form_tags displaynotification %}

{% block pagetitle %} {{ project.name }} | Edit {{ milestone.title }} {% endblock %}

{% block jquerypluginloader %}
<script src="/media/js/jquery/jquery.ui.js" type="text/javascript" charset="utf-8"></script>
<script src="/media/js/jquery/ui/i18n/ui.datepicker-{{LANGUAGE_CODE}}.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/media/js/jquery/ui.theme.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
 <link rel="stylesheet" href="/media/js/jquery/ui.datepicker.css" type="text/css" media="screen" title="core css file" charset="utf-8" />
{% endblock %}

{% block jquerycode %}
     $(document).ready(function(){
        $('#id_due_date').datepicker({
        nextText: '',
        prevText: '',
        showOn: 'both',
        buttonImage: '/media/basepage/images/icons/date_add.png',
        buttonImageOnly: true ,
        buttonText: 'Calendar',
        yearRange: '2008:2020',
        dateFormat: 'yy-mm-dd'});
     });
{% endblock %}

{% block area_name %}
    <p>{% trans "Edit milestone" %}</p>
{% endblock %}

{% block menu %}
	{% genmenu "inproject" "milestones" project.id %}
{% endblock %}

{% block right_content %}
{% endblock %}

{% block main_content %}

	{% displaynotification messages %}

    <form action="{% url milestone.views.edit p_id=project.id,milestone_id=milestone.id %}" method="post">
    	{% beginrequestbox "required" _("Milestone") _("All these fields are required")  %}
			{% printfield  newMilestone.title "left" %}
			{% printfield  newMilestone.responsible "left" %}
			{% printfield  newMilestone.due_date "left" %}
	    {% endrequestbox %}

		{% beginrequestbox "notrequired" _("Other Info") _("All fields in this section are optional.")  %}
			{% printfield  newMilestone.send_notification_email "right" %}
	    {% endrequestbox %}

		{% printformfooter _("Update Milestone") _("Cancel") "rancho.milestone.views.list project.id" %}
    </form>
{% endblock %}

rancho/templates/milestone/milestones_list.html
{% extends "project/basicproject.html" %}

{% load i18n usernamegen modalconfirm genmenu displaymilestone displaynotification permissions_tags %}

{% block pagetitle %} {{ project.name }} | {% trans "View Milestones" %} {% endblock %}


{% block jquerypluginloader %}
<script type="text/javascript" src="/media/js/jquery/simplemodal.js"></script>
{% endblock %}

{% block jquerycode %}
    function delete_milestone(milestone_id) {
        url = '{% url rancho.milestone.views.delete project.id,111111 %}';
        window.location = url.replace(/111111/g,milestone_id);
        return false;
    }
	function complete_milestone(milestone_id) {
	    url = '{% url rancho.milestone.views.complete project.id,111111 %}';
        window.location = url.replace(/111111/g,milestone_id);
        return false;
    }
	function incomplete_milestone(milestone_id) {
        url = '{% url rancho.milestone.views.incomplete project.id,111111 %}';
        window.location = url.replace(/111111/g,milestone_id);
        return false;
    }

{% endblock %}

{% block area_name %}
    <p>{% trans "Milestones" %}</p>
{% endblock %}

{% block menu %}
	{% genmenu "inproject" "milestones" project.id %}
{% endblock %}

{% block mini_menu %}
	{% if view_alone %}
		<br/>
		<a href="{% url milestone.views.list project.id %}">{% trans "Back to milestones list" %}</a>
	{% endif %}
{% endblock %}

{% block right_content %}
	{% ifhasperm "PERMISSIONS_MILESTONE_CREATE" user project  %}
	    <div class="add_button">
	        <a href="{% url milestone.views.create p_id=project.id %}">{% trans "New Milestone" %}</a>
	    </div>
	    <div class="add_button_right"></div>
	    <br/><br/>
	{% endifhasperm %}
{% endblock %}


{% block main_content %}

	{% displaynotification messages %}
	{% if not late_milestones and not upcoming_milestones and not complete_milestones %}
	    <p>{% trans "There are no milestones in this project yet." %}</p>
	{% endif %}

    {% if late_milestones %}
		<p style="margin-bottom: 10px;">
			{% if view_alone %}
				<span class="smallcaps_title red_bg white">{% trans "Late Milestones" %}</span>
			{% else %}
				<a class="smallcaps_title red_bg white" href="{% url list_with_status p_id=project.id,status="late" %}">{% trans "Late Milestones" %}</a>
			{% endif %}
		</p>
		{% for milestone in late_milestones %}
			{% displaymilestone milestone "red" user %}
		{% endfor %}
	{% endif %}
	{% if upcoming_milestones %}
		<p style="margin-bottom: 10px;">
			{% if view_alone %}
				<span class="smallcaps_title blue_bg white">{% trans "Upcoming Milestones" %}</span>
			{% else %}
				<a class="smallcaps_title blue_bg white" href="{% url list_with_status p_id=project.id,status="upcoming" %}">{% trans "Upcoming Milestones" %}</a>
			{% endif %}
		</p>
		{% for milestone in upcoming_milestones %}
			{% displaymilestone milestone "blue" user %}
		{% endfor %}
	{% endif %}
	{% if complete_milestones %}
		<p style="margin-bottom: 10px;">
			{% if view_alone %}
				<span class="smallcaps_title green_bg white">{% trans "Complete Milestones" %}</span>
			{% else %}
				<a class="smallcaps_title green_bg white" href="{% url list_with_status p_id=project.id,status="complete" %}">{% trans "Complete Milestones" %}</a>
			{% endif %}
		</p>
		{% for milestone in complete_milestones %}
			{% displaymilestone milestone "green" user %}
		{% endfor %}
	{% endif %}
{% endblock %}